### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by luthermonson**
@jlehtimaki I don't have a better way to get a hold of you so here's a PR, I sort of blew your drone-exporter up a bit and improved it. If you'd like to talk about how we can get this merged in and keep working on it together I'm all ears, if you'd prefer I just hard fork it let me know that too. If you think you want this stuff just respond back and I'll make it a better PR for you to merge and we can discuss maintenance of the older version. Either way thanks for the inspiration, cheers.

### CODE REVIEW

**Comment by luthermonson** [comment]
fyi this is still even a WIP for what we're doing so it will still change but the core concepts will remain intact. Take a look at the README for more details of what I actually did, it'll probably make a lot of sense to you.

**Comment by jlehtimaki** [comment]
Hey thanks @luthermonson! 
Of course I'm open to improvements and willing to work with you / you guys :)
Let me check the code and I'll get back to you on this!

**Comment by jlehtimaki** [comment]
@luthermonson this looks good and good improvements, let me know if I can help somehow.

**Comment by luthermonson** [comment]
@jlehtimaki thanks! still making changes to running against two drone api servers etc but it's come together nicely. ill go over some more details, email me directly (from my profile) or if that's you in the k8s slack (one person has your name in search) send me a message

**Comment by jlehtimaki** [comment]
Good work @luthermonson I'll just remove the vendor files which I think is not needed because of go.mod :+1:

**Pull request merged**
